"""
Async SQLite interface for mori-orchestrator using aiosqlite.

Key design decisions:
- WAL mode for concurrent readers + one writer.
- ULID primary keys everywhere (generated by callers).
- Status strings are Spanish to match Mori v2 convention.
- FTS5 virtual table on tasks and notes for memory retrieval.
- Atomic claim of pending tasks via a single UPDATE + SELECT.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Optional

import aiosqlite
import structlog

log = structlog.get_logger()

_SCHEMA = """
PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- ------------------------------------------------------------------
-- Projects
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    description     TEXT,
    area            TEXT NOT NULL
                    CHECK(area IN ('personal','empresa','proyecto','sistema','salud','finanzas','otro')),
    tags            TEXT,           -- JSON array
    working_dir     TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ------------------------------------------------------------------
-- Tasks
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
    id              TEXT PRIMARY KEY,
    project_id      TEXT REFERENCES projects(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    description     TEXT,
    status          TEXT NOT NULL DEFAULT 'pendiente'
                    CHECK(status IN ('pendiente','en_progreso','completada','bloqueada','cancelada')),
    priority        TEXT NOT NULL DEFAULT 'media'
                    CHECK(priority IN ('critica','alta','media','baja')),
    area            TEXT,
    tags            TEXT,           -- JSON array
    pipeline_id     TEXT,
    assigned_agent  TEXT,
    result          TEXT,
    error           TEXT,
    cost_usd        REAL DEFAULT 0.0,
    claimed_at      TEXT,
    completed_at    TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- FTS5 index on tasks for memory retrieval
CREATE VIRTUAL TABLE IF NOT EXISTS tasks_fts USING fts5(
    title,
    description,
    tags,
    content='tasks',
    content_rowid='rowid'
);

-- Triggers to keep FTS in sync
CREATE TRIGGER IF NOT EXISTS tasks_ai AFTER INSERT ON tasks BEGIN
    INSERT INTO tasks_fts(rowid, title, description, tags)
    VALUES (new.rowid, new.title, new.description, new.tags);
END;
CREATE TRIGGER IF NOT EXISTS tasks_ad AFTER DELETE ON tasks BEGIN
    INSERT INTO tasks_fts(tasks_fts, rowid, title, description, tags)
    VALUES ('delete', old.rowid, old.title, old.description, old.tags);
END;
CREATE TRIGGER IF NOT EXISTS tasks_au AFTER UPDATE ON tasks BEGIN
    INSERT INTO tasks_fts(tasks_fts, rowid, title, description, tags)
    VALUES ('delete', old.rowid, old.title, old.description, old.tags);
    INSERT INTO tasks_fts(rowid, title, description, tags)
    VALUES (new.rowid, new.title, new.description, new.tags);
END;

-- ------------------------------------------------------------------
-- Notes (knowledge base)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notes (
    id          TEXT PRIMARY KEY,
    project_id  TEXT REFERENCES projects(id) ON DELETE SET NULL,
    title       TEXT NOT NULL,
    content     TEXT NOT NULL,
    tags        TEXT,           -- JSON array
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(
    title,
    content,
    tags,
    content='notes',
    content_rowid='rowid'
);

CREATE TRIGGER IF NOT EXISTS notes_ai AFTER INSERT ON notes BEGIN
    INSERT INTO notes_fts(rowid, title, content, tags)
    VALUES (new.rowid, new.title, new.content, new.tags);
END;
CREATE TRIGGER IF NOT EXISTS notes_ad AFTER DELETE ON notes BEGIN
    INSERT INTO notes_fts(notes_fts, rowid, title, content, tags)
    VALUES ('delete', old.rowid, old.title, old.content, old.tags);
END;
CREATE TRIGGER IF NOT EXISTS notes_au AFTER UPDATE ON notes BEGIN
    INSERT INTO notes_fts(notes_fts, rowid, title, content, tags)
    VALUES ('delete', old.rowid, old.title, old.content, old.tags);
    INSERT INTO notes_fts(rowid, title, content, tags)
    VALUES (new.rowid, new.title, new.content, new.tags);
END;

-- ------------------------------------------------------------------
-- Agent runs  (one row per pipeline step execution)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_runs (
    id                  TEXT PRIMARY KEY,
    task_id             TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    agent_id            TEXT NOT NULL,
    model_id            TEXT NOT NULL,
    pipeline_id         TEXT,
    phase               TEXT,
    status              TEXT NOT NULL DEFAULT 'running'
                        CHECK(status IN ('running','completed','failed','cancelled')),
    prompt_tokens       INTEGER DEFAULT 0,
    completion_tokens   INTEGER DEFAULT 0,
    cost_usd            REAL DEFAULT 0.0,
    turns_used          INTEGER DEFAULT 0,
    duration_seconds    REAL,
    output              TEXT,
    error               TEXT,
    started_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    finished_at         TEXT
);

-- ------------------------------------------------------------------
-- Streaming chunks  (picked up by SSE endpoint)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS run_streams (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id      TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    chunk       TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ------------------------------------------------------------------
-- Daily metrics  (aggregated at finish_task time)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS daily_metrics (
    date            TEXT NOT NULL,
    model_id        TEXT NOT NULL,
    agent_id        TEXT NOT NULL,
    tasks_completed INTEGER DEFAULT 0,
    tasks_failed    INTEGER DEFAULT 0,
    prompt_tokens   INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    cost_usd        REAL DEFAULT 0.0,
    PRIMARY KEY (date, model_id, agent_id)
);
"""


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


class Database:
    """Async SQLite wrapper for mori-orchestrator."""

    def __init__(self, path: str) -> None:
        self.path = path
        self._conn: Optional[aiosqlite.Connection] = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def _get_conn(self) -> aiosqlite.Connection:
        if self._conn is None:
            self._conn = await aiosqlite.connect(self.path)
            self._conn.row_factory = aiosqlite.Row
            await self._conn.execute("PRAGMA journal_mode=WAL")
            await self._conn.execute("PRAGMA foreign_keys=ON")
            await self._conn.execute("PRAGMA synchronous=NORMAL")
            await self._conn.execute("PRAGMA cache_size=-32000")  # ~32 MB
        return self._conn

    async def initialize(self) -> None:
        """Create all tables and FTS indices if they do not exist."""
        conn = await self._get_conn()
        # Execute schema in one shot (executescript needs a raw connection)
        await conn.executescript(_SCHEMA)
        await conn.commit()
        log.info("database_initialized", path=self.path)

    async def close(self) -> None:
        if self._conn:
            await self._conn.close()
            self._conn = None

    # ------------------------------------------------------------------
    # Internal helper
    # ------------------------------------------------------------------

    async def _fetchall(self, sql: str, params: tuple = ()) -> list[dict]:
        conn = await self._get_conn()
        async with conn.execute(sql, params) as cur:
            rows = await cur.fetchall()
            return [dict(r) for r in rows]

    async def _fetchone(self, sql: str, params: tuple = ()) -> Optional[dict]:
        conn = await self._get_conn()
        async with conn.execute(sql, params) as cur:
            row = await cur.fetchone()
            return dict(row) if row else None

    def _decode_tags(self, row: dict) -> dict:
        """Parse JSON tags field into a Python list in-place."""
        if row.get("tags") and isinstance(row["tags"], str):
            try:
                row["tags"] = json.loads(row["tags"])
            except (json.JSONDecodeError, TypeError):
                row["tags"] = []
        return row

    # ------------------------------------------------------------------
    # Task operations
    # ------------------------------------------------------------------

    async def claim_pending_tasks(self, limit: int = 4) -> list[dict]:
        """
        Atomically claim up to *limit* pending tasks by setting their
        status to 'en_progreso'.  Returns the claimed rows.
        """
        conn = await self._get_conn()
        now = _now_iso()

        # Collect IDs to claim
        async with conn.execute(
            """
            SELECT id FROM tasks
            WHERE status = 'pendiente'
            ORDER BY
                CASE priority
                    WHEN 'critica' THEN 1
                    WHEN 'alta'    THEN 2
                    WHEN 'media'   THEN 3
                    WHEN 'baja'    THEN 4
                    ELSE 5
                END,
                created_at ASC
            LIMIT ?
            """,
            (limit,),
        ) as cur:
            ids = [r[0] async for r in cur]

        if not ids:
            return []

        placeholders = ",".join("?" * len(ids))
        await conn.execute(
            f"""
            UPDATE tasks
            SET status = 'en_progreso', claimed_at = ?, updated_at = ?
            WHERE id IN ({placeholders})
            """,
            (now, now, *ids),
        )
        await conn.commit()

        rows = await self._fetchall(
            f"SELECT * FROM tasks WHERE id IN ({placeholders})", tuple(ids)
        )
        return [self._decode_tags(r) for r in rows]

    async def finish_task(
        self,
        task_id: str,
        result: str,
        cost_usd: float,
        agent_id: Optional[str] = None,
        model_id: Optional[str] = None,
    ) -> None:
        """Mark a task as completada."""
        conn = await self._get_conn()
        now = _now_iso()
        await conn.execute(
            """
            UPDATE tasks
            SET status = 'completada',
                result = ?,
                cost_usd = ?,
                assigned_agent = COALESCE(?, assigned_agent),
                completed_at = ?,
                updated_at = ?
            WHERE id = ?
            """,
            (result, cost_usd, agent_id, now, now, task_id),
        )
        await conn.commit()
        log.info("task_completed", task_id=task_id, cost_usd=cost_usd)

    async def fail_task(self, task_id: str, error: str) -> None:
        """Mark a task as bloqueada with an error message."""
        conn = await self._get_conn()
        now = _now_iso()
        await conn.execute(
            """
            UPDATE tasks
            SET status = 'bloqueada',
                error = ?,
                updated_at = ?
            WHERE id = ?
            """,
            (error, now, task_id),
        )
        await conn.commit()
        log.warning("task_failed", task_id=task_id, error=error)

    async def get_task(self, task_id: str) -> Optional[dict]:
        row = await self._fetchone("SELECT * FROM tasks WHERE id = ?", (task_id,))
        return self._decode_tags(row) if row else None

    # ------------------------------------------------------------------
    # Agent run operations
    # ------------------------------------------------------------------

    async def create_agent_run(
        self,
        task_id: str,
        agent_id: str,
        model_id: str,
        pipeline_id: Optional[str],
        phase: str,
    ) -> str:
        """Insert a new agent_run row and return its ID."""
        from ulid import ULID

        run_id = str(ULID())
        conn = await self._get_conn()
        await conn.execute(
            """
            INSERT INTO agent_runs
                (id, task_id, agent_id, model_id, pipeline_id, phase, status, started_at)
            VALUES (?, ?, ?, ?, ?, ?, 'running', ?)
            """,
            (run_id, task_id, agent_id, model_id, pipeline_id, phase, _now_iso()),
        )
        await conn.commit()
        return run_id

    async def finish_agent_run(
        self,
        run_id: str,
        output: str,
        status: str,
        prompt_tokens: int,
        completion_tokens: int,
        cost_usd: float,
        turns_used: int,
    ) -> None:
        """Update an agent_run on completion or failure."""
        conn = await self._get_conn()
        now = _now_iso()
        await conn.execute(
            """
            UPDATE agent_runs
            SET output = ?,
                status = ?,
                prompt_tokens = ?,
                completion_tokens = ?,
                cost_usd = ?,
                turns_used = ?,
                finished_at = ?,
                duration_seconds = (
                    CAST((julianday(?) - julianday(started_at)) * 86400.0 AS REAL)
                )
            WHERE id = ?
            """,
            (
                output, status, prompt_tokens, completion_tokens,
                cost_usd, turns_used, now, now, run_id,
            ),
        )
        await conn.commit()

    async def fail_agent_run(self, run_id: str, error: str) -> None:
        conn = await self._get_conn()
        now = _now_iso()
        await conn.execute(
            """
            UPDATE agent_runs
            SET status = 'failed', error = ?, finished_at = ?
            WHERE id = ?
            """,
            (error, now, run_id),
        )
        await conn.commit()

    async def get_agent_run(self, run_id: str) -> Optional[dict]:
        return await self._fetchone(
            "SELECT * FROM agent_runs WHERE id = ?", (run_id,)
        )

    # ------------------------------------------------------------------
    # Streaming
    # ------------------------------------------------------------------

    async def append_stream_chunk(self, run_id: str, chunk: str) -> None:
        """Insert a text chunk into run_streams."""
        conn = await self._get_conn()
        await conn.execute(
            "INSERT INTO run_streams (run_id, chunk) VALUES (?, ?)",
            (run_id, chunk),
        )
        await conn.commit()

    async def get_stream_chunks(
        self, run_id: str, after_id: int = 0
    ) -> list[dict]:
        """Return chunks for *run_id* with id > *after_id* (for SSE polling)."""
        return await self._fetchall(
            """
            SELECT id, chunk, created_at
            FROM run_streams
            WHERE run_id = ? AND id > ?
            ORDER BY id ASC
            """,
            (run_id, after_id),
        )

    # ------------------------------------------------------------------
    # Memory / FTS search
    # ------------------------------------------------------------------

    async def search_notes_fts(self, query: str, limit: int = 5) -> list[dict]:
        """Full-text search on notes using FTS5."""
        try:
            # Sanitise query — wrap in quotes to avoid FTS5 syntax errors
            safe_query = query.replace('"', '""')
            return await self._fetchall(
                """
                SELECT n.id, n.title, n.content, n.tags, n.updated_at
                FROM notes n
                JOIN notes_fts nf ON n.rowid = nf.rowid
                WHERE notes_fts MATCH ?
                ORDER BY rank
                LIMIT ?
                """,
                (safe_query, limit),
            )
        except Exception as exc:
            log.warning("notes_fts_failed", error=str(exc))
            return []

    async def search_similar_tasks(self, query: str, limit: int = 3) -> list[dict]:
        """Full-text search on completed / blocked tasks."""
        try:
            safe_query = query.replace('"', '""')
            return await self._fetchall(
                """
                SELECT t.id, t.title, t.status, t.tags, t.updated_at
                FROM tasks t
                JOIN tasks_fts tf ON t.rowid = tf.rowid
                WHERE tasks_fts MATCH ?
                  AND t.status IN ('completada', 'bloqueada')
                ORDER BY rank
                LIMIT ?
                """,
                (safe_query, limit),
            )
        except Exception as exc:
            log.warning("tasks_fts_failed", error=str(exc))
            return []

    # ------------------------------------------------------------------
    # Metrics helpers
    # ------------------------------------------------------------------

    async def upsert_daily_metrics(
        self,
        date: str,
        model_id: str,
        agent_id: str,
        completed: int = 0,
        failed: int = 0,
        prompt_tokens: int = 0,
        completion_tokens: int = 0,
        cost_usd: float = 0.0,
    ) -> None:
        conn = await self._get_conn()
        await conn.execute(
            """
            INSERT INTO daily_metrics
                (date, model_id, agent_id, tasks_completed, tasks_failed,
                 prompt_tokens, completion_tokens, cost_usd)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(date, model_id, agent_id) DO UPDATE SET
                tasks_completed  = tasks_completed  + excluded.tasks_completed,
                tasks_failed     = tasks_failed     + excluded.tasks_failed,
                prompt_tokens    = prompt_tokens    + excluded.prompt_tokens,
                completion_tokens= completion_tokens+ excluded.completion_tokens,
                cost_usd         = cost_usd         + excluded.cost_usd
            """,
            (
                date, model_id, agent_id, completed, failed,
                prompt_tokens, completion_tokens, cost_usd,
            ),
        )
        await conn.commit()

    async def get_daily_stats(self, date: str) -> dict:
        row = await self._fetchone(
            """
            SELECT
                SUM(tasks_completed)   AS tasks_completed,
                SUM(tasks_failed)      AS tasks_failed,
                SUM(prompt_tokens)     AS prompt_tokens,
                SUM(completion_tokens) AS completion_tokens,
                SUM(cost_usd)          AS cost_usd
            FROM daily_metrics
            WHERE date = ?
            """,
            (date,),
        )
        return row or {}

    async def get_model_stats(self, date: Optional[str] = None) -> list[dict]:
        if date:
            return await self._fetchall(
                """
                SELECT model_id, SUM(tasks_completed) AS tasks_completed,
                       SUM(cost_usd) AS cost_usd,
                       SUM(prompt_tokens) AS prompt_tokens,
                       SUM(completion_tokens) AS completion_tokens
                FROM daily_metrics WHERE date = ?
                GROUP BY model_id
                ORDER BY cost_usd DESC
                """,
                (date,),
            )
        return await self._fetchall(
            """
            SELECT model_id, SUM(tasks_completed) AS tasks_completed,
                   SUM(cost_usd) AS cost_usd,
                   SUM(prompt_tokens) AS prompt_tokens,
                   SUM(completion_tokens) AS completion_tokens
            FROM daily_metrics
            GROUP BY model_id
            ORDER BY cost_usd DESC
            """
        )
